# Generated by Django 4.0.2 on 2023-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cAddr',
            field=models.CharField(blank='True', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='cEmail',
            field=models.EmailField(blank='True', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='cPhone',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
    ]
